name = "equational_theories"
defaultTargets = ["equational_theories"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[require]]
name = "«doc-gen4»"
git = "https://github.com/leanprover/doc-gen4"
rev = "main"

[[lean_lib]]
name = "equational_theories"

[[lean_exe]]
name = "extract_implications"
root = "scripts.extract_implications"
supportInterpreter = true

[[require]]
name = "egg"
git  = "https://github.com/marcusrossel/lean-egg"
rev  = "main"

# until this tactic is upstreamed we want to run it as compiled code
[[lean_lib]]
name = "DecideBang"
root = "DecideBang"
precompileModules = true
