[package]
name = "magmaegg"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
bytemuck = { version = "1.18.0", features = ["bytemuck_derive", "extern_crate_std"] }
bytemuck_derive = "1.7.1"
clap = { version = "4.5.19", features = ["derive"] }
egg = { version = "0.9.5", features = ["serde", "serde-1"] }
fxhash = "0.2.1"
itertools = "0.13.0"
libc = "0.2.159"
nix = { version = "0.29.0", features = ["process"] }
regex = "1.11.0"
ron = "0.8.1"
serde = "1.0.210"
serde_derive = "1.0.210"
smallvec = "1.13.2"
symbolic_expressions = "5.0.3"
tempfile = "3.13.0"
zstd = "0.13.2"
